### ISSUE TITLE
直播看球软件或者手机safari播放无法投屏

### ISSUE THREAD

**Issue by Chris-L727** [suaptv/UnPlay#1]
用直播app选择unplay投屏，屏幕会显示“FFMpeg打开视频失败！”；
用手机safari播放视频，投屏无法找到unplay，能找到电视自带的乐播投屏和homepod 这些（用咪咕这些视频app能找到unplay投屏，所以应该也不是网段问题）；

**Comment by suaptv** [comment]
dlna协议苹果自家产品怎么可能支持呢？
这个是需要客户端软件支持dlna才能投，safari是的airplay
留下email或软件上面找联系方式，这上面不适合具体讨论,我看看这个信息怎么删除吧

**Comment by suaptv** [comment]
safari支持离线投屏了只是部分网站支持,如果网站直接提供了视频地址，因为这种方式不是流式投屏（和镜像一样原理）

**Comment by suaptv** [comment]
目前已经提供更为详细的报错信息，可以清楚知道为什么投屏不了
