### ISSUE TITLE
视频投屏成功但无法播放

### ISSUE THREAD

**Issue by cairy** [suaptv/UnPlay#3]
视频地址：https://mp.weixin.qq.com/s/nmUG_Ah5vY7eMZS2bFdEHA
投屏成功但无法播放，显示“FFMpeg打开视频失败！”。

**Comment by suaptv** [comment]
这个是网页地址，不是视频播放地址

**Comment by cairy** [comment]
> 这个是网页地址，不是视频播放地址

是个网页，在alook浏览器中打开开始播放视频再推送，推送成功但无法播放。

**Comment by suaptv** [comment]
这上面视频不能拿出来播放，有权限认证
