### ISSUE TITLE
【需求】实现AppleTV不打开app也能直接投屏

### ISSUE THREAD

**Issue by hu1994101** [suaptv/UnPlay#7]
不知道作者能否可以实现？类似开机自启这种功能，不进入app也能随时投屏
@suaptv

**Comment by suaptv** [comment]
没有这样可能的，苹果就是获取进程信息现在都封锁的，连设备名字都是。用苹果就老老实实的
其实有些东西是需要客户端实现的，现实基本不可能了
还有所谓后台模式，那个只是后台驻留，稳定性堪忧的
最重要的还是得打开APP啊，不打开混啥?
这些毫无意义

**Comment by hu1994101** [comment]
好的，感谢作者解惑。还有个问题想问问，如果投屏的app只支持airplay，选择unplay能正常投屏成功吗？ @suaptv

**Comment by suaptv** [comment]
safari支持的
